version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "${MQTT_PORT:-1883}:1883"
    volumes:
      - ./apps/mqtt-broker/config:/mosquitto/config
      - ./apps/mqtt-broker/data:/mosquitto/data
      - ./apps/mqtt-broker/log:/mosquitto/log
    restart: unless-stopped
